name: "Netlify CLI"
description: "Wraps the Netlify CLI and offers access to deploy outputs"
author: "Alex Gabites <https://github.com/South-Paw>"
branding:
  color: purple
  icon: cloud
inputs:
  args:
    description: 'Any command from https://cli.netlify.com/commands (without the `netlify` prefix) and its arguments (e.g. `deploy --json --dir "./public" --message "Hello world!"`'
    required: true
runs:
  using: composite
  steps:
    - id: script
      run: $GITHUB_ACTION_PATH/action.sh ${{ inputs.args }}
      shell: bash
outputs:
  NETLIFY_OUTPUT:
    description: "Raw Netlify CLI output message"
    value: ${{ steps.script.outputs.NETLIFY_OUTPUT }}
  NETLIFY_LOGS_URL:
    description: "URL to Netlify deployment logs"
    value: ${{ fromJson(steps.script.outputs.NETLIFY_OUTPUT).logs }}
  NETLIFY_DRAFT_URL:
    description: "URL to draft site"
    value: ${{ fromJson(steps.script.outputs.NETLIFY_OUTPUT).deploy_url }}
  NETLIFY_PROD_URL:
    description: "URL to production site"
    value: ${{ fromJson(steps.script.outputs.NETLIFY_OUTPUT).url }}
